title: Blog of Life
author: Ronjia Nellemann
email: goldami@mailo.com
description: Blog of life is discussing current crises and and obstacles towards a better future.
Every week, I chose a subject that has a great impact on life and how we can adapt new ideas and solutions, 
to manage our lives in a way that supports planet earth, rather than the opposite.

# social links

github_username:  dragonfly232

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
